name: ci

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - uses: actions/cache@v3
        id: deps-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - if: steps.deps-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - run: pnpm run lint

      - name: build core
        working-directory: packages/core
        run: |
          pnpm install
          pnpm run build

      - run: pnpm run test

      - name: build demo
        working-directory: demo/react
        run: pnpm run build
