name: ci

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/cache@v3
        id: deps-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/cache@v3
        id: demo-react-deps-cache
        with:
          path: demo/react/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('demo/react/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('demo/react/yarn.lock') }}-
            ${{ runner.os }}-yarn-

      - if: steps.deps-cache.outputs.cache-hit != 'true'
        run: yarn install
        
      - if: steps.demo-react-deps-cache.outputs.cache-hit != 'true'
        run: yarn --cwd demo/react install

      - run: yarn run lint
      - run: yarn run build
      - run: yarn run test
