name: ci

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/cache@v3
        id: deps-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - run: pnpm run lint

      - name: build core
        working-directory: packages/core
        run: |
          pnpm install
          pnpm run build

      # - name: Build agent
      #   working-directory: packages/agent
      #   run: |
      #     pnpm install
      #     pnpm run build

      - run: pnpm run test

      - name: build demo
        working-directory: demo/react
        run: pnpm run build
